name: Deployment Test

on:
  push:
    branches: [ main ]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in Azure
        env:
            PRIVATE_KEY: ${{ secrets.AZURE_PRIVATE_KEY  }}
            # HOSTNAME : ${{ secrets.HOSTNAME  }}
            # USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key azurebikku@20.187.110.247 '

            cd /home/azurebikku/Deployment_Test &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main 
          '
